---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services
- Utilities:
    - Portainer:
        href: https://portainer.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Portainer
        icon: portainer.png
        server: my-docker
        container: portainer
        widget:
            type: portainer
            env: 2
            url: https://portainer.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
            key: apikey # Update with api key

    - Traefik:
        href: https://traefik.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Traefik
        icon: traefik.png
        server: my-docker
        container: traefik
        widget:
            type: traefik
            url: https://traefik.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
            username: username # Update with your corresponding username
            password: password # Update with your corresponding password

    - Pi-hole:
        href: https://pihole.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Pi-hole
        icon: pi-hole.png
        server: my-docker
        container: pihole
        widget:
            type: pihole
            url: http://pihole.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
            key: apikey # Update with api key
#            username: username # Update with your corresponding username
#            password: password # Update with your corresponding password

    - Prometheus:
        href: https://prometheus.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Prometheus
        icon: prometheus.png
        server: my-docker
        container: prometheus
        widget:
            type: prometheus
            url: https://prometheus.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
#            username: username # Update with your corresponding username
#            password: password # Update with your corresponding password

    - Grafana:
        href: https://grafana.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Grafana
        icon: grafana.png
        server: my-docker
        container: grafana
        widget:
            type: grafana
            url: https://grafana.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
            username: username # Update with your corresponding username
            password: password # Update with your corresponding password

    - Uptime-kuma:
        href: https://uptimekuma.subdomain.mydomain.org # Update with your domain address configured in .env file next to the do>
        description: Uptime kuma
        icon: uptime-kuma.png
        server: my-docker
        container: uptime-kuma

    - Minidlna:
        href: https://minidlna.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docke>
        description: Minidlna
        icon: dlna.png
        server: my-docker
        container: minidlna

    - micrOS:
        href: https://micros.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docke>
        description: micrOS
        icon: python.png
        server: my-docker
        container: micros-gateway

    - Whoami:
        href: https://whoami.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker->
        description: Whoami
        icon: webtools.png
        server: my-docker
        container: whoami

    - Router Local:
        href: http://router.local.ip # Update with your router's local address
        description: Router Local
        icon: asus-router.png

    - Router Remote:
        href: https://router.external.ip # Update with your router's remote address
        description: Router Remote
        icon: asus-router.png

    - Yacht:
        href: https://yacht.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Yacht
        icon: yacht.png
        server: my-docker
        container: yacht

- Media and Files:
    - qBittorrent:
        href: https://qbittorrent.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: qBittorrent
        icon: qbittorrent.png
        server: my-docker
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://qbittorrent.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
            username: username # Update with your corresponding username
            password: password # Update with your corresponding password

    - Plex:
        href: https://plex.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compo>
        description: Plex
        icon: plex.png
        server: my-docker
        container: plex
        widget:
            type: plex
            url: https://plex.subdomain.mydomain.org
            key: mykeygoeshere # see https://www.plexopedia.com/plex-media-server/general/plex-token/

    - Tautulli:
        href: https://tautulli.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docke>
        description: Tautulli
        icon: tautulli.png
        server: my-docker
        container: tautulli
        widget:
            type: tautulli
            url: https://tautulli.subdomain.mydomain.org # Update with your domain address configured in .env file
            key: apikey # update with apikey from tautulli website: settings/web interface/api key
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true

    - Jellyfin:
        href: https://jellyfin.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Jellyfin
        icon: jellyfin.png
        server: my-docker
        container: jellyfin
        widget:
            type: jellyfin
            url: http://jellyfin.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
            key: apikey # Update with api key
            enableBlocks: true
            enableNowPlaying: true

    - Nextcloud:
        href: https://nextcloud.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.>
        description: Nextcloud
        icon: nextcloud.png
        server: my-docker
        container: nextcloud
        widget:
            type: nextcloud
            url: https://nextcloud.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.>
            username: username
            password: password

    - Calibre-web:
        href: https://calibreweb.subdomain.mydomain.org # Update with your domain address configured in .env file next to the dock>
        description: Calibre-Web
        icon: calibre-web.png
        server: my-docker
        container: calibre-web
        widget:
            type: calibreweb
            url: https://calibreweb.subdomain.mydomain.org # Update with your domain address configured in .env file
            username: username
            password: password

    - Filebrowser:
        href: https://filebrowser.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Filebrowser
        icon: filebrowser.png
        server: my-docker
        container: filebrowser

    - Duplicati:
        href: https://duplicati.subdomain.mydomain.org
        description: Duplicati
        icon: duplicati.png
        server: my-docker
        container: duplicati

    - Ntfy:
        href: https://ntfy.subdomain.mydomain.org
        description: Ntfy
        icon: ntfy.png
        server: my-docker
        container: ntfy

- Other:
#    - Yacht:
#        href: https://yacht.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-c>
#        description: Yacht
#        icon: yacht.png
#        server: my-docker
#        container: yacht

#    - Heimdall:
#        href: https://heimdall.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
#        description: Heimdall
#        icon: heimdall.png
#        server: my-docker
#        container: heimdall

    - Homeassistant:
        href: https://homeassistant.subdomain.mydomain.org # Update with your domain address configured in .env file next to the doc>
        description: Homeassistant
        icon: home-assistant.png
        server: my-docker
        container: homeassistant
        widget:
            type: homeassistant
            url: https://homeassistant.subdomain.mydomain.org # Update with your domain address configured in .env file next to the doc>
            key: key # Update with your key

    - Excalidraw:
        href: https://excalidraw.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Excalidraw
        icon: excalidraw.png
        server: my-docker
        container: excalidraw

    - Mealie:
        href: https://mealie.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Mealie
        icon: mealie.png
        server: my-docker
        container: mealie

    - Wikijs:
        href: https://wikijs.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Wikijs
        icon: wikijs.png
        server: my-docker
        container: wikijs

    - Dokuwiki:
        href: https://dokuwiki.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Dokuwiki
        icon: dokuwiki.png
        server: my-docker
        container: dokuwiki

    - Librespeed:
        href: https://librespeed.subdomain.mydomain.org # Update with your domain address configured in .env file next to the docker-compose.yaml
        description: Librespeed
        icon: librespeed.png
        server: my-docker
        container: librespeed
