version: "3.8"
services:
  ###### Traefik ######
  traefik:
    command:
      - "traefik"
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.file=true"
      - "--providers.file.filename=/etc/traefik/rules.toml"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.email=${CERT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - '--entryPoints.http=true'
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      #- '--entryPoints.http.forwardedHeaders.insecure=false'
      #- '--entryPoints.http.proxyProtocol.insecure=false'
      - "--entrypoints.http.forwardedHeaders.trustedIPs=${AUTHELIA_TRUSTED_IPS}"
      - "--entryPoints.http.proxyProtocol.trustedIPs=${AUTHELIA_TRUSTED_IPS}"
      - '--entryPoints.https=true'
      - "--entrypoints.https.address=:443"
      #- '--entryPoints.https.forwardedHeaders.insecure=false'
      #- '--entryPoints.https.proxyProtocol.insecure=false'
      - "--entrypoints.https.forwardedHeaders.trustedIPs=${AUTHELIA_TRUSTED_IPS}"
      - "--entryPoints.https.proxyProtocol.trustedIPs=${AUTHELIA_TRUSTED_IPS}"
      - "--metrics"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=traefik"
      - "--metrics.prometheus.buckets=${PROMETHEUS_BUCKETS}"
    container_name: "traefik"
    image: "traefik:latest"
    depends_on:
      - authelia
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.entrypoints: "https"
      traefik.http.routers.api.rule: "Host(`${TRAEFIK_TRAEFIK_HOST}`)"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.api.tls.certresolver: "myresolver"
      traefik.http.routers.api.middlewares: "basic-auth@docker"
      traefik.http.middlewares.basic-auth.basicauth.users: ${ADMIN_USER}:${ADMIN_PASSWORD},${USER1}:${USER1_PASSWORD}
    network_mode: "bridge"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    restart: "unless-stopped"
    environment:
      - "TZ=${TZ}"
    volumes:
      - "/etc/traefik/rules.yml:${CONFIG_PATH}/traefik/rules.yml"
      - "${CONFIG_PATH}/letsencrypt:/letsencrypt"
      - "${CONFIG_PATH}/traefik/rules.toml:/etc/traefik/rules.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"

  ###### Authelia ######
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - "${CONFIG_PATH}/authelia/:/config"
    network_mode: "bridge"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`${TRAEFIK_AUTHELIA_HOST}`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls.certresolver=myresolver'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=https://${TRAEFIK_AUTHELIA_HOST}/api/verify?rd=https://${TRAEFIK_AUTHELIA_HOST}'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      # Authelia is also capable of http basicauth, so it can be used for that also instead of the built-in one from traefik middlewares
      #- 'traefik.http.middlewares.authelia-basic.forwardAuth.address=https://${TRAEFIK_AUTHELIA_HOST}/api/verify?auth=basic' # Middleware name will be authelia-basic@docker
      #- 'traefik.http.middlewares.authelia-basic.forwardAuth.trustForwardHeader=true'
      #- 'traefik.http.middlewares.authelia-basic.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    ports:
      - "9091:9091"
    restart: unless-stopped
    environment:
      - "TZ=${TZ}"
    healthcheck:
      disable: true # when false, the container takes 10-20s to come up

  ###### Prometheus ######
  prometheus:
    container_name: "prometheus"
    image: prom/prometheus
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
    ports:
      - "9090:9090"
    volumes:
      - ${CONFIG_PATH}/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - "--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME}"
      - "--storage.tsdb.retention.size=${PROMETHEUS_RETENTION_SIZE}"
    network_mode: "bridge"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.entrypoints: "https"
      traefik.http.routers.prometheus.rule: "Host(`${TRAEFIK_PROMETHEUS_HOST}`)"
      traefik.http.routers.prometheus.tls.certresolver: "myresolver"
      traefik.http.routers.prometheus.service: "prometheus"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
      traefik.docker.network: "bridge"
      traefik.http.routers.prometheus.middlewares: authelia@docker
    restart: "unless-stopped"

  ###### Prometheus node-exporter ######
  prometheus-node-exporter:
    image: prom/node-exporter:latest
    container_name: prometheus-node-exporter
    restart: unless-stopped
    environment:
      - "TZ=${TZ}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    network_mode: "bridge"

  ###### Grafana ######
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ${CONFIG_PATH}/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ${CONFIG_PATH}/grafana/config.monitoring
    network_mode: "bridge"
    environment:
      - "TZ=${TZ}"
    user: "472" # this means, that the username is admin
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.entrypoints: "https"
      traefik.http.routers.grafana.rule: "Host(`${TRAEFIK_GRAFANA_HOST}`)"
      traefik.http.routers.grafana.tls.certresolver: "myresolver"
      traefik.http.routers.grafana.service: "grafana"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      traefik.docker.network: "bridge"
      traefik.http.routers.grafana.middlewares: authelia@docker
    restart: unless-stopped

  ###### Portainer ######
  portainer:
    container_name: "portainer"
    image: "portainer/portainer-ce"
    network_mode: "bridge"
    ports:
      - "9000:9000/tcp"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

  ###### Whoami ######
  whoami:
    container_name: "whoami"
    image: "traefik/whoami:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.entrypoints: "https"
      traefik.http.routers.whoami.rule: "Host(`${TRAEFIK_WHOAMI_HOST}`)"
      traefik.http.routers.whoami.tls: "true"
      traefik.http.routers.whoami.tls.certresolver: "myresolver"
      traefik.http.routers.whoami.middlewares: authelia@docker
    network_mode: "bridge"
    restart: "unless-stopped"
    environment:
      - "TZ=${TZ}"

  ###### Samba ######
  samba:
    command:
      - "-n"
      - "-u"
      - "${SAMBA_USERNAME};${SAMBA_PASSWORD}"
      - "-s"
      - "shared;/rpi_shared;yes;no;no;admin;admin;admin"
      - "-s"
      - "docker_compose;/docker_compose;yes;no;no;admin;admin;admin"
      - "-s"
      - "rpi_brew;/rpi_brew;yes;no;no;admin;admin;admin"
      - "-p"
    container_name: "samba"
    image: "dperson/samba:latest"
    network_mode: "bridge"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: "unless-stopped"
    volumes:
      - "var_cache_samba:/var/cache/samba"
      - "var_lib_samba:/var/lib/samba"
      - "var_log_samba:/var/log/samba"
      - "etc_samba:/etc"
      - "run_samba:/run/samba"
      - "${HDD_PATH_SHARED}:/rpi_shared"
      - "/home/pi/rpi_brew:/rpi_brew" # TODO remove
      - "/home/pi/docker_compose:/docker_compose" # TODO remove

  ###### Minidlna ######
  minidlna:
    container_name: "minidlna"
    environment:
      - "MINIDLNA_MEDIA_DIR=/media"
      - "MINIDLNA_FRIENDLY_NAME=${MINIDLNA_FRIENDLY_NAME}"
    image: "vladgh/minidlna:latest"
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - "${HDD_PATH_SHARED}:/media"

  ###### Wikijs ######
  wikijs:
    container_name: "wikijs"
    image: "linuxserver/wikijs:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.wikijs.entrypoints: "https"
      traefik.http.routers.wikijs.rule: "Host(`${TRAEFIK_WIKIJS_HOST}`)"
      traefik.http.routers.wikijs.tls.certresolver: "myresolver"
      traefik.http.routers.wikijs.middlewares: authelia@docker
    network_mode: "bridge"
    ports:
      - "3100:3000/tcp"
    restart: "unless-stopped"
    volumes:
      - "${CONFIG_PATH}/wikijs/data:/data"
      - "${CONFIG_PATH}/wikijs:/config"

  ###### Librespeed ######
  librespeed:
    container_name: "librespeed"
    image: "linuxserver/librespeed:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.librespeed.entrypoints: "https"
      traefik.http.routers.librespeed.rule: "Host(`${TRAEFIK_LIBRESPEED_HOST}`)"
      traefik.http.routers.librespeed.tls.certresolver: "myresolver"
      traefik.http.routers.librespeed.middlewares: "authelia@docker"
    network_mode: "bridge"
    restart: "unless-stopped"
    volumes:
      - "librespeed_data:/config"

  ###### Fliebrowser ######
  filebrowser:
    container_name: "filebrowser"
    image: "hurlenko/filebrowser:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.filebrowser.entrypoints: "https"
      traefik.http.routers.filebrowser.rule: "Host(`${TRAEFIK_FILEBROWSER_HOST}`)"
      traefik.http.routers.filebrowser.tls.certresolver: "myresolver"
      traefik.http.routers.filebrowser.middlewares: "authelia@docker"
    network_mode: "bridge"
    ports:
      - "8081:8081/tcp"
    restart: "unless-stopped"
    volumes:
      - "${CONFIG_PATH}/filebrowser:/config"
      - "${HDD_PATH_SHARED}:/data"

  ###### Duplicati ######
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
    volumes:
      - ${CONFIG_PATH}/duplicati:/config
      - ${HDD_PATH}/_backup:/backups
      - /home/pi/docker_compose/:/source_docker_compose
      - /home/pi/docker_appdata/:/source_docker_appdata
      - /home/pi/rpi_brew/:/source_rpi_brew
      - /home/pi/.bash_aliases:/.bash_aliases
      - /home/pi/.gitconfig:/.gitconfig
      - "duplicati_source:/source"

    labels:
      traefik.enable: "true"
      traefik.http.routers.duplicati.entrypoints: "https"
      traefik.http.routers.duplicati.rule: "Host(`${TRAEFIK_DUPLICATI_HOST}`)"
      traefik.http.routers.duplicati.tls.certresolver: "myresolver"
      traefik.http.routers.duplicati.middlewares: "authelia@docker"
    ports:
      - 8300:8300
    network_mode: "bridge"
    restart: unless-stopped

  ###### Jellyfin ######
  jellyfin:
    container_name: "jellyfin"
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
    image: "linuxserver/jellyfin:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.entrypoints: "https"
      traefik.http.routers.jellyfin.rule: "Host(`${TRAEFIK_JELLYFIN_HOST}`)"
      traefik.http.routers.jellyfin.tls.certresolver: "myresolver"
      traefik.http.routers.jellyfin.middlewares: authelia@docker
    network_mode: "bridge"
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
    restart: "unless-stopped" # in case resource limits are set, you have to use "always" to make sure the container is getting automatically back to a healty state in case of reaching the pre-set resource limits
    volumes:
      - "${CONFIG_PATH}/jellyfin:/config"
      - "${JELLYFIN_CACHE}:/cache"
      - "${JELLYFIN_METADATA}/:/metadata"
      - "${JELLYFIN_TRANSCODE_CACHE}:/transcodes"
      - "${HDD_PATH_SHARED}:/shared_downloads"
    #cpus: 0.5 # in my case from 0.1 to 4, the max value can be found here: docker info | grep -iE "CPUs|Memory"
    #mem_limit: 1g # in my case the max is 3.7g, max value can be found here: docker info | grep -iE "CPUs|Memory"
    #mem_reservation: 128M

  ###### Dokuwiki ######
  dokuwiki:
    container_name: "dokuwiki"
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
    image: "ghcr.io/linuxserver/dokuwiki:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dokuwiki.entrypoints: "https"
      traefik.http.routers.dokuwiki.rule: "Host(`${TRAEFIK_DOKUWIKI_HOST}`)"
      traefik.http.routers.dokuwiki.tls.certresolver: "myresolver"
      traefik.http.routers.dokuwiki.middlewares: authelia@docker
    network_mode: "bridge"
    restart: "unless-stopped"
    volumes:
      - "${CONFIG_PATH}/dokuwiki:/config"

  ###### Dynu Updater ######
  dynu-updater:
    container_name: "dynu-updater"
    environment:
      - "TZ=${TZ}"
      - "USERNAME=${USERNAME}"
      - "PASSWORD=${PASSWORD}"
      - "HOSTNAMES=${HOSTNAMES}"
      - "REFRESH_TIME=${REFRESH_TIME}"
    image: "dokeraj/dynu-updater:latest"
    network_mode: "bridge"
    restart: "unless-stopped"
    ports:
      - "1050:1050"

#  ###### Duckdns ######
#  duckdns:
#    container_name: "duckdns"
#    environment:
#      - "PGID=${PGID}"
#      - "PUID=${PUID}"
#      - "TZ=${TZ}"
#      - "SUBDOMAINS=${SUBDOMAINS}"
#      - "TOKEN=${TOKEN}"
#    image: "linuxserver/duckdns:latest"
#    network_mode: "bridge"
#    restart: "unless-stopped"
#    volumes:
#      - "${CONFIG_PATH}/duckdns:/config"

  ###### Watchtower ######
  watchtower:
    container_name: "watchtower"
    environment:
      - "WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}"
      - "WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}"
    image: "containrrr/watchtower:latest"
    network_mode: "bridge"
    restart: "unless-stopped"
    stdin_open: true
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  ###### Qbittorrent ######
  qbittorrent:
    container_name: "qbittorrent"
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
      - "UMASK=022"
      - "WEBUI_PORT=${WEBUI_PORT}"
    image: "linuxserver/qbittorrent:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.qbittorrent.entrypoints: "https"
      traefik.http.routers.qbittorrent.rule: "Host(`${TRAEFIK_QBITTORRENT_HOST}`)"
      traefik.http.routers.qbittorrent.tls.certresolver: "myresolver"
      traefik.http.routers.qbittorrent.middlewares: authelia@docker
    network_mode: "bridge"
    ports:
      - "5555:5555/tcp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
    restart: "unless-stopped"
    volumes:
      - "${CONFIG_PATH}/qbittorrent:/config"
      - "${HDD_PATH_SHARED}/downloads:/downloads"

  ###### Pihole ######
  pihole:
    container_name: "pihole"
    environment:
      - "TZ=${TZ}"
      - "WEBPASSWORD=${WEBPASSWORD}"
      - "DNSMASQ_USER=${DNSMASQ_USER}"
      - "VIRTUAL_HOST=${TRAEFIK_PIHOLE_HOST}"
    image: "pihole/pihole:latest"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.pihole-admin.addprefix.prefix: "/admin"
      traefik.http.routers.pihole.rule: "Host(`${TRAEFIK_PIHOLE_HOST}`)"
      traefik.http.routers.pihole.service: "pihole"
      traefik.http.routers.pihole.tls: "true"
      traefik.http.routers.pihole.tls.certresolver: "myresolver"
      traefik.http.routers.pihole_http.entrypoints: "http"
      traefik.http.routers.pihole_http.middlewares: "authelia@docker, pihole-admin"
      traefik.http.routers.pihole_http.rule: "Host(`${TRAEFIK_PIHOLE_HOST}`)"
      traefik.http.services.pihole.loadBalancer.server.port: "80"
      traefik.http.routers.pihole.middlewares: authelia@docker
    network_mode: "bridge"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "88:80/tcp"
    restart: "unless-stopped"
    volumes:
      - "${CONFIG_PATH}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "${CONFIG_PATH}/pihole/etc-pihole:/etc/pihole"

  ###### Heimdall ######
  heimdall:
    container_name: "heimdall"
    environment:
      - "TZ=${TZ}"
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    image: "lscr.io/linuxserver/heimdall:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.heimdall.entrypoints: "https"
      traefik.http.routers.heimdall.rule: "Host(`${TRAEFIK_HEIMDALL_HOST}`)"
      traefik.http.routers.heimdall.tls.certresolver: "myresolver"
      traefik.http.routers.heimdall.middlewares: authelia@docker
    network_mode: "bridge"
    restart: "unless-stopped"
    volumes:
      - "${CONFIG_PATH}/heimdall:/config"

  ###### Homepage ######
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3001:3000
    environment:
      - "TZ=${TZ}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.entrypoints: "https"
      traefik.http.routers.homepage.rule: "Host(`${TRAEFIK_DEFAULT_HOST}`, `${TRAEFIK_HOMEPAGE_HOST}`)"
      traefik.http.routers.homepage.tls.certresolver: "myresolver"
      traefik.http.routers.homepage.middlewares: authelia@docker
    volumes:
      - ${CONFIG_PATH}/homepage/:/app/config
      - ${HDD_PATH}/:/mnt/hdd:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    network_mode: "bridge"

  ###### Yacht ######
  yacht:
    container_name: "yacht"
    image: "selfhostedpro/yacht:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.yacht.entrypoints: "https"
      traefik.http.routers.yacht.rule: "Host(`${TRAEFIK_YACHT_HOST}`)"
      traefik.http.routers.yacht.tls.certresolver: "myresolver"
      traefik.http.routers.yacht.middlewares: authelia@docker
    network_mode: "bridge"
    ports:
      - "8001:8000/tcp"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "yacht_data:/config"

volumes:
  portainer_data: {}
  yacht_data: {}
  librespeed_data: {}
  duplicati_source: {}
  prometheus_data: {}
  grafana_data: {}
  var_cache_samba: {}
  var_lib_samba: {}
  var_log_samba: {}
  etc_samba: {}
  run_samba: {}