{
 "title": "David NUC System Basic Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "System basic info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System Uptime",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load (5m avg)",
   "type": "stat",
   "description": "System Load (5m avg)",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load (15m avg)",
   "type": "stat",
   "description": "System Load (15m avg)",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SSD Total",
   "type": "stat",
   "description": "SSD Total",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDD Total",
   "type": "stat",
   "description": "HDD Total",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/usb0\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System basic gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "CPU System Load (1m avg)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "gauge",
   "description": "CPU System Load (5m avg)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU System Load (15m avg)",
   "type": "gauge",
   "description": "CPU System Load (15m avg)",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15) / count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "gauge",
   "description": "Used SWAP",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used SSD",
   "type": "gauge",
   "description": "Used SSD",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used HDD",
   "type": "gauge",
   "description": "Used HDD",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/usb0\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/usb0\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System basic graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "RAM Free" },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{ chip }} {{ sensor }} temp" },
    {
     "expr": "node_hwmon_temp_crit_celsius",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  { "title": "System detailed graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "Memory Committed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes",
     "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
    },
    {
     "expr": "node_memory_CommitLimit_bytes",
     "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes",
     "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes",
     "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
    },
    {
     "expr": "node_memory_Active_file_bytes",
     "legendFormat": "Active_file - File-backed memory on active LRU list"
    },
    {
     "expr": "node_memory_Active_anon_bytes",
     "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs'} - node_filesystem_avail_bytes{device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}