{
 "title": "David NUC Logs Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {}
   },
   {
    "name": "filename",
    "label": "filename",
    "query": {}
   },
   {
    "name": "container_name",
    "label": "container_name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "System Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of stdout lines",
   "type": "stat",
   "description": "Number of stdout lines",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\", filename=\"$filename\"} |= `` [$__interval])"
    }
   ]
  },
  {
   "title": "Number of stderr lines",
   "type": "stat",
   "description": "Number of stderr lines",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\", filename=\"$filename\"} |= `` [$__interval])"
    }
   ]
  },
  {
   "title": "System Logs",
   "type": "logs",
   "description": "System Logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{job=\"$job\", filename=\"$filename\"}"
    }
   ]
  },
  { "title": "Container Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Number of stdout lines",
   "type": "stat",
   "description": "Number of stdout lines",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container_name=\"$container_name\", source=\"stdout\"} |= `` [$__interval])"
    }
   ]
  },
  {
   "title": "Number of stderr lines",
   "type": "stat",
   "description": "Number of stderr lines",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({container_name=\"$container_name\", source=\"stderr\"} |= `` [$__interval])"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "description": "Container Logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container_name=\"$container_name\"}"
    }
   ]
  }
 ]
}