apiVersion: 1

deleteDatasources:
  - name: Prometheus
#  - name: Prometheus-local

datasources:
- name: Prometheus
  type: prometheus
  access: browser
  # Add your prometheus domain name here
  url: http://prometheus.mydomain.something.com
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
     keepCookies: ["authelia_session"]
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
# Sample for adding second prometheus data source
#- name: Prometheus-local
#  type: prometheus
#  access: browser
#  # Add your prometheus IP and port here
#  url: http://192.168.0.5:9090
#  password:
#  user:
#  database:
#  basicAuth: false
#  basicAuthUser:
#  basicAuthPassword:
#  withCredentials:
#  isDefault: false
#  jsonData:
#     graphiteVersion: "1.1"
#     tlsAuth: false
#     tlsAuthWithCACert: false
#  secureJsonData:
#    tlsCACert: "..."
#    tlsClientCert: "..."
#    tlsClientKey: "..."
#  version: 1
#  editable: true
- name: Loki-local
  type: loki
  access: proxy
  # TODO Add your Loki IP and port here
  url: http://192.168.X.Y:3100
  url: "http://192.168.50.245:3100"
  jsonData:
    maxLines: 1000
