services:
  ###### Dokuwiki ######
  dokuwiki:
    container_name: "dokuwiki"
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
    image: "ghcr.io/linuxserver/dokuwiki:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.dokuwiki.entrypoints: "websecure"
      traefik.http.routers.dokuwiki.rule: "Host(`${TRAEFIK_DOKUWIKI_HOST}`)"
      traefik.http.routers.dokuwiki.tls.certresolver: "myresolver"
      traefik.http.routers.dokuwiki.middlewares: authelia@docker
    networks:
      - homelab
    restart: "unless-stopped"
    volumes:
      - "${CONFIG_PATH}/dokuwiki:/config"

  ###### Excalidraw ######
  excalidraw:
    container_name: excalidraw
    image: docker.io/excalidraw/excalidraw:latest
    ports:
      - 8003:80
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
    networks:
      - homelab
    restart: "unless-stopped"
    labels:
      traefik.enable: "true"
      traefik.http.routers.excalidraw.entrypoints: "websecure"
      traefik.http.routers.excalidraw.rule: "Host(`${TRAEFIK_EXCALIDRAW_HOST}`)"
      traefik.http.routers.excalidraw.tls.certresolver: "myresolver"
      traefik.http.routers.excalidraw.middlewares: authelia@docker

  ###### Homeassistant ######
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:latest"
    container_name: homeassistant
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - 8123:8123
    volumes:
      - ${CONFIG_PATH}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - "/var/run/dbus:/var/run/dbus"
      - "/run/dbus:/run/dbus"
      - "/var/lib/bluetooth:/var/lib/bluetooth"
      - "/etc/bluetooth:/etc/bluetooth"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    environment:
      - "TZ=${TZ}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homeassistant.entrypoints: "websecure"
      traefik.http.routers.homeassistant.rule: "Host(`${TRAEFIK_HA_HOST}`)"
      traefik.http.routers.homeassistant.tls.certresolver: "myresolver"
      traefik.http.routers.homeassistant.middlewares: authelia@docker
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123

  ###### Librespeed ######
  librespeed:
    container_name: "librespeed"
    image: "linuxserver/librespeed:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.librespeed.entrypoints: "websecure"
      traefik.http.routers.librespeed.rule: "Host(`${TRAEFIK_LIBRESPEED_HOST}`)"
      traefik.http.routers.librespeed.tls.certresolver: "myresolver"
      traefik.http.routers.librespeed.middlewares: "authelia@docker"
    networks:
      - homelab
    restart: "unless-stopped"
    environment:
      - "TZ=${TZ}"
    volumes:
      - "librespeed_data:/config"

  ###### Mealie ######
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    ports:
      - 9925:9000
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
      - "BASE_URL=${TRAEFIK_MEALIE_HOST}"
    volumes:
    - ${CONFIG_PATH}/mealie:/app/data
    networks:
      - homelab
    restart: "unless-stopped"
    labels:
      traefik.enable: "true"
      traefik.http.routers.mealie.entrypoints: "websecure"
      traefik.http.routers.mealie.rule: "Host(`${TRAEFIK_MEALIE_HOST}`)"
      traefik.http.routers.mealie.tls.certresolver: "myresolver"
      traefik.http.routers.mealie.middlewares: authelia@docker

  ###### micrOS ######
  micros-gateway:
    image: bxnxm/micros-gateway:1.59.4
    container_name: micros-gateway
    environment:
      - "TZ=${TZ}"
      - GATEWAYIP=${GATEWAY_IP}
    ports:
      - "5000:5000"  # Expose Flask REST API port to host
    networks:
      - homelab
    restart: "unless-stopped"
    labels:
      traefik.enable: "true"
      traefik.http.routers.micros-gateway.entrypoints: "websecure"
      traefik.http.routers.micros-gateway.rule: "Host(`${TRAEFIK_MICROS_HOST}`)"
      traefik.http.routers.micros-gateway.tls.certresolver: "myresolver"
      traefik.http.routers.micros-gateway.middlewares: authelia@docker

  ###### Wikijs ######
  wikijs:
    container_name: "wikijs"
    image: "linuxserver/wikijs:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.wikijs.entrypoints: "websecure"
      traefik.http.routers.wikijs.rule: "Host(`${TRAEFIK_WIKIJS_HOST}`)"
      traefik.http.routers.wikijs.tls.certresolver: "myresolver"
      traefik.http.routers.wikijs.middlewares: authelia@docker
    networks:
      - homelab
    ports:
      - "4000:3000/tcp"
    restart: "unless-stopped"
    environment:
      - "TZ=${TZ}"
    volumes:
      - "${CONFIG_PATH}/wikijs/data:/data"
      - "${CONFIG_PATH}/wikijs:/config"

networks:
  homelab:
    name: homelab
    driver: bridge
    external: false

volumes:
  librespeed_data: {}
