apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Prometheus-local
  - name: Loki-local

datasources:
- name: Prometheus
  type: prometheus
  access: browser
  # Add your prometheus domain name here
  url: http://prometheus.mydomain.example.com
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
     keepCookies: ["authelia_session"]
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
- name: Prometheus-local
  type: prometheus
  access: browser
    # Add your prometheus domain name here
  url: http://prometheus:9090
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: false
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
- name: Loki-local
  type: loki
  access: proxy
  url: "http://loki:3100"
  jsonData:
    maxLines: 1000
  editable: true
